### ISSUE TITLE
Scrobbling (SLS) Support?

### ISSUE THREAD

**Issue by a-r-db** [avs333/alsaplayer#1]
[Simple Last.fm Scrobbler](https://github.com/tgwizard/sls) users hope that alsaplayer will [support scrobbling](https://github.com/tgwizard/sls/issues/23).

**Comment by avs333** [comment]
I'm sorry, but this player never supported scrobbling until skvalex has done it in some intermediate version. It'd be a matter of seconds should he send me the code again!
